
CREATE TABLE FLIGHTS (
  DAY_OF_WEEK INTEGER,
  FL_DATE TEXT,
  UNIQUE_CARRIER TEXT,
  FL_NUM INTEGER,
  ORIGIN TEXT,
  ORIGIN_CITY_NAME TEXT,
  ORIGIN_STATE_ABR TEXT,
  ORIGIN_STATE_NM TEXT,
  DEST TEXT,
  DEST_CITY_NAME TEXT,
  DEST_STATE_ABR TEXT,
  DEST_STATE_NM TEXT,
  DEP_DELAY REAL,
  ARR_DELAY REAL,
  CANCELLED REAL,
  CANCELLATION_CODE TEXT,
  DIVERTED REAL,
  AIR_TIME REAL,
  DISTANCE REAL
);

CREATE INDEX flights_carrier ON flights (unique_carrier);
CREATE INDEX flights_date ON flights (fl_date);
CREATE INDEX flights_origin ON flights (origin);
CREATE INDEX flights_dest ON flights (dest);
