
CREATE TABLE FLIGHTS (
  DAY_OF_WEEK INTEGER,
  FL_DATE TEXT,
  UNIQUE_CARRIER TEXT,
  FL_NUM INTEGER,
  ORIGIN TEXT,
  ORIGIN_CITY_NAME TEXT,
  ORIGIN_STATE_ABR TEXT,
  ORIGIN_STATE_NM TEXT,
  DEST TEXT,
  DEST_CITY_NAME TEXT,
  DEST_STATE_ABR TEXT,
  DEST_STATE_NM TEXT,
  DEP_DELAY REAL,
  ARR_DELAY REAL,
  CANCELLED REAL,
  CANCELLATION_CODE TEXT,
  DIVERTED REAL,
  AIR_TIME REAL,
  DISTANCE REAL
);
